import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#FAF4E4',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '92%',
    paddingTop: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  title: { fontSize: 18, fontWeight: '700', color: '#0147B9', flexShrink: 1 },
  closeText: { fontSize: 18, color: '#a3a3a3' },
  infoBox: {
    paddingHorizontal: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E8D9B8',
    gap: 4,
  },
  infoText: { fontSize: 13, color: '#a3a3a3' },
  list: { paddingHorizontal: 24 },
  listContent: { gap: 12, paddingVertical: 16 },
  placeholder: { color: '#a3a3a3', fontSize: 14, textAlign: 'center', marginVertical: 12 },
  reviewCard: {
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E8D9B8',
    padding: 12,
    gap: 6,
  },
  reviewText: { fontSize: 14, color: '#171717' },
  reviewDate: { fontSize: 11, color: '#a3a3a3' },
  miEtiqueta: { fontSize: 11, fontWeight: '700', color: '#0147B9' },
  formBox: {
    marginTop: 8,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E8D9B8',
    gap: 12,
  },
  formTitle: { fontSize: 15, fontWeight: '700', color: '#0147B9' },
  textarea: {
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E8D9B8',
    backgroundColor: '#FAF4E4',
    padding: 12,
    fontSize: 14,
    color: '#171717',
    textAlignVertical: 'top',
    minHeight: 80,
  },
  errorText: { fontSize: 12, fontWeight: '500', color: '#dc2626' },
});
